from backend.app.models.delivery_point import DeliveryPoint, DeliveryPointStatus, DeliveryPointStatusHistory, DeliveryPointType
from backend.app.models.client import (
    Client,
    ClientAddress,
    ClientBankAccount,
    ClientContact,
    ClientDocument,
    ClientNote,
)
from backend.app.models.geo import District, Region
from backend.app.models.contract import (
    Contract,
    ContractDocument,
    ContractItem,
    ContractNote,
    ContractPaymentTerms,
    ContractTransportTerms,
)
from backend.app.models.order import (
    Order,
    OrderDocument,
    OrderItem,
    OrderNote,
    OrderSupplierOption,
)
from backend.app.models.delivery import (
    DeliveryBatch,
    DeliveryBatchDocument,
    DeliveryBatchItem,
    DeliveryBatchNote,
    Logistics,
    LogisticsDocument,
    LogisticsNote,
)
from backend.app.models.finance import (
    CustomerInvoice,
    CustomerInvoiceItem,
    CustomerPayment,
    FinanceDocument,
    FinanceNote,
    PaymentAllocation,
)
from backend.app.models.procurement import (
    Procurement,
    ProcurementDocument,
    ProcurementItem,
    ProcurementNote,
    Supplier,
    SupplierAddress,
    SupplierBankAccount,
    SupplierContact,
    SupplierDocument,
    SupplierNote,
    SupplierOffer,
    SupplierOfferItem,
)
from backend.app.models.supplier_finance import (
    SupplierFinanceDocument,
    SupplierFinanceNote,
    SupplierInvoice,
    SupplierInvoiceItem,
    SupplierPayment,
    SupplierPaymentAllocation,
)
from backend.app.models.inventory import (
    ExchangeTicket,
    StockAllocation,
    StockLocation,
    StockLot,
    StockMovement,
)
from backend.app.models.transport import Transport, TransportCheckIn, TransportEvent, TransportRepair, TransportRepairPart
from backend.app.models.product import Product, ProductCategory
from backend.app.models.customer_request import (
    CompanyRegistry,
    CustomerRequest,
    CustomerRequestSchedule,
    CustomerRequestStatusHistory,
)
from backend.app.models.audit import AuditLog
from backend.app.models.attendance import AttendanceRecord, Department, Employee, HikvisionSyncLog
from backend.app.models.task import Notification, Task, TaskAssignee, TaskAttachment, TaskComment, TaskHistory
from backend.app.models.user import User

__all__ = [
    "Region",
    "District",
    "Client",
    "DeliveryPoint",
    "DeliveryPointType",
    "DeliveryPointStatus",
    "DeliveryPointStatusHistory",
    "ClientAddress",
    "ClientBankAccount",
    "ClientContact",
    "ClientDocument",
    "ClientNote",
    "Contract",
    "ContractDocument",
    "ContractItem",
    "ContractNote",
    "ContractPaymentTerms",
    "ContractTransportTerms",
    "Order",
    "OrderDocument",
    "OrderItem",
    "OrderNote",
    "OrderSupplierOption",
    "DeliveryBatch",
    "DeliveryBatchDocument",
    "DeliveryBatchItem",
    "DeliveryBatchNote",
    "Logistics",
    "LogisticsDocument",
    "LogisticsNote",
    "CustomerInvoice",
    "CustomerInvoiceItem",
    "CustomerPayment",
    "FinanceDocument",
    "FinanceNote",
    "PaymentAllocation",
    "Procurement",
    "ProcurementDocument",
    "ProcurementItem",
    "ProcurementNote",
    "Supplier",
    "SupplierAddress",
    "SupplierBankAccount",
    "SupplierContact",
    "SupplierDocument",
    "SupplierNote",
    "SupplierOffer",
    "SupplierOfferItem",
    "SupplierFinanceDocument",
    "SupplierFinanceNote",
    "SupplierInvoice",
    "SupplierInvoiceItem",
    "SupplierPayment",
    "SupplierPaymentAllocation",
    "ExchangeTicket",
    "StockAllocation",
    "StockLocation",
    "StockLot",
    "StockMovement",
    "Transport",
    "TransportCheckIn",
    "TransportEvent",
    "TransportRepair",
    "TransportRepairPart",
    "Product",
    "ProductCategory",
    "CompanyRegistry",
    "CustomerRequest",
    "CustomerRequestSchedule",
    "CustomerRequestStatusHistory",
    "AuditLog",
    "AttendanceRecord",
    "HikvisionSyncLog",
    "Department",
    "Employee",
    "Task",
    "TaskAssignee",
    "TaskAttachment",
    "TaskComment",
    "TaskHistory",
    "Notification",
    "User",
]
