const app = document.querySelector("#app");
const toast = document.querySelector("#toast");
const dash = "—";

const addressTypes = [
  ["legal", "Yuridik"],
  ["delivery", "Yetkazish"],
  ["railway_station", "Temir yo'l bekati"],
  ["warehouse", "Ombor"],
];

const documentTypes = [
  ["requisites", "Rekvizitlar"],
  ["certificate", "Sertifikat"],
  ["power_of_attorney", "Ishonchnoma"],
  ["company_card", "Korxona kartasi"],
  ["other", "Boshqa"],
];

const contractStatuses = [
  ["draft", "Qoralama"],
  ["signed", "Imzolangan"],
  ["active", "Faol"],
  ["completed", "Yakunlangan"],
  ["expired", "Muddati tugagan"],
  ["cancelled", "Bekor qilingan"],
];

const contractDocumentTypes = [
  ["contract_pdf", "Shartnoma PDF"],
  ["specification", "Spetsifikatsiya"],
  ["additional_agreement", "Qo'shimcha kelishuv"],
  ["invoice", "Hisob-faktura"],
  ["act", "Dalolatnoma"],
  ["other", "Boshqa"],
];

const orderStatuses = [
  ["draft", "Qoralama"],
  ["created", "Yaratilgan"],
  ["supplier_search", "Ta'minotchi qidirilmoqda"],
  ["supplier_selected", "Ta'minotchi tanlangan"],
  ["supplier_confirmed", "Ta'minotchi tasdiqlangan"],
  ["waiting_payment", "To'lov kutilmoqda"],
  ["ready_for_delivery", "Yetkazishga tayyor"],
  ["in_delivery", "Yetkazilmoqda"],
  ["partially_delivered", "Qisman yetkazildi"],
  ["delivered", "Yetkazildi"],
  ["documents_pending", "Hujjatlar kutilmoqda"],
  ["closed", "Yopildi"],
  ["on_hold", "To'xtatib turilgan"],
  ["cancelled", "Bekor qilingan"],
];

const fulfillmentTypes = [
  ["direct_supplier_to_customer", "To'g'ridan-to'g'ri"],
  ["company_managed_delivery", "Biz boshqaramiz"],
];

const sourceTypes = [
  ["russia_direct", "Rossiyadan to'g'ridan-to'g'ri"],
  ["uzbekistan_local", "O'zbekiston ichki bozor"],
  ["jarkurgan", "Jarqo'rg'on"],
  ["supplier_held_stock", "Ta'minotchi omboridagi zaxira"],
  ["other", "Boshqa"],
];

const exchangeTicketStatuses = [
  ["draft", "Qoralama"],
  ["opened", "Ochilgan"],
  ["partially_paid", "Qisman to'langan"],
  ["paid", "To'langan"],
  ["overdue", "Muddati o'tgan"],
  ["closed", "Yopilgan"],
  ["cancelled", "Bekor qilingan"],
];

const stockLocationTypes = [
  ["supplier_storage", "Ta'minotchi ombori"],
  ["company_warehouse", "Kompaniya ombori"],
  ["in_transit", "Yo'lda"],
  ["customer_site", "Mijoz hududi"],
  ["other", "Boshqa"],
];

const ticketPaymentTypes = [
  ["spot", "Spot"],
  ["forward", "Forward"],
];

const stockStatuses = [
  ["available", "Mavjud"],
  ["reserved", "Band qilingan"],
  ["partially_used", "Qisman ishlatilgan"],
  ["used", "Ishlatilgan"],
  ["blocked", "Bloklangan"],
  ["cancelled", "Bekor qilingan"],
];

const stockAllocationStatuses = [
  ["reserved", "Band qilingan"],
  ["released", "Banddan chiqarilgan"],
  ["picked_up", "Olib ketilgan"],
  ["delivered", "Yetkazilgan"],
  ["cancelled", "Bekor qilingan"],
];

const stockMovementTypes = [
  ["purchase_in", "Xarid kirimi"],
  ["reserve", "Band qilish"],
  ["release_reserve", "Banddan chiqarish"],
  ["pickup", "Olib ketish"],
  ["in_transit", "Yo'lda"],
  ["delivered", "Yetkazildi"],
  ["adjustment", "Tuzatish"],
];

const supplierStatuses = [
  ["not_selected", "Tanlanmagan"],
  ["searching", "Qidirilmoqda"],
  ["selected", "Tanlangan"],
  ["confirmed", "Tasdiqlangan"],
  ["changed", "O'zgartirilgan"],
];

const orderDocumentTypes = [
  ["order_request", "Buyurtma so'rovi"],
  ["supplier_offer", "Ta'minotchi taklifi"],
  ["supplier_confirmation", "Ta'minotchi tasdig'i"],
  ["internal_file", "Ichki fayl"],
  ["other", "Boshqa"],
];

const batchStatuses = [
  ["planned", "Rejada"],
  ["supplier_preparing", "Ta'minotchi tayyorlamoqda"],
  ["ready_for_loading", "Yuklashga tayyor"],
  ["waiting_payment", "To'lov kutilmoqda"],
  ["loading", "Yuklanmoqda"],
  ["loaded", "Yuklandi"],
  ["in_transit", "Yo'lda"],
  ["arrived", "Qabul qilinmoqda"],
  ["unloading", "Tushirilmoqda"],
  ["accepted", "Qabul qilindi"],
  ["quantity_difference", "Miqdor farqi bor"],
  ["documents_pending", "Hujjatlar kutilmoqda"],
  ["completed", "Yakunlandi"],
  ["cancelled", "Bekor qilindi"],
  ["issue", "Muammo"],
];

const logisticsStatuses = [
  ["not_assigned", "Biriktirilmagan"],
  ["carrier_assigned", "Tashuvchi biriktirilgan"],
  ["vehicle_assigned", "Transport biriktirilgan"],
  ["loading", "Yuklanmoqda"],
  ["loaded", "Yuklandi"],
  ["in_transit", "Yo'lda"],
  ["arrived", "Yetib keldi"],
  ["unloading", "Tushirilmoqda"],
  ["delivered", "Yetkazildi"],
  ["accepted", "Qabul qilindi"],
  ["completed", "Yakunlandi"],
  ["cancelled", "Bekor qilingan"],
  ["issue", "Muammo"],
];

const paidByTypes = [
  ["company", "Kompaniya"],
  ["customer", "Mijoz"],
  ["supplier", "Ta'minotchi"],
];

const batchDocumentTypes = [
  ["ttn", "TTN"],
  ["acceptance_act", "Qabul dalolatnomasi"],
  ["quality_certificate", "Sifat sertifikati"],
  ["supplier_invoice", "Ta'minotchi hisobi"],
  ["customer_invoice", "Mijoz hisobi"],
  ["photo", "Foto"],
  ["other", "Boshqa"],
];

const invoiceTypes = [["advance", "Avans"], ["batch_payment", "Partiya to'lovi"], ["transport", "Transport"], ["adjustment", "Qayta hisoblash"], ["other", "Boshqa"]];
const invoiceStatuses = [["draft", "Qoralama"], ["issued", "Yuborilgan"], ["partially_paid", "Qisman to'langan"], ["paid", "To'langan"], ["overdue", "Kechikkan"], ["cancelled", "Bekor qilingan"]];
const paymentMethods = [["bank_transfer", "Bank orqali"], ["cash", "Naqd"], ["other", "Boshqa"]];
const paymentStatuses = [["received", "Kelib tushgan"], ["unallocated", "Taqsimlanmagan"], ["partially_allocated", "Qisman taqsimlangan"], ["allocated", "Taqsimlangan"], ["cancelled", "Bekor qilingan"]];
const financeDocumentTypes = [["invoice_file", "Hisob fayli"], ["payment_order", "To'lov topshiriqnomasi"], ["bank_statement", "Bank ko'chirmasi"], ["reconciliation_act", "Solishtirma dalolatnoma"], ["other", "Boshqa"]];

const supplierAddressTypes = [["legal", "Yuridik"], ["loading", "Yuklash"], ["warehouse", "Ombor"], ["factory", "Zavod"], ["other", "Boshqa"]];
const procurementStatuses = [["draft", "Qoralama"], ["supplier_search", "Ta'minotchi qidirilmoqda"], ["offers_received", "Takliflar olindi"], ["supplier_selected", "Ta'minotchi tanlandi"], ["supplier_confirmed", "Ta'minotchi tasdiqlandi"], ["purchase_approved", "Xarid tasdiqlandi"], ["waiting_supplier_ready", "Ta'minotchi tayyorligi kutilmoqda"], ["ready_for_pickup", "Yuklab olishga tayyor"], ["ready_for_delivery", "Yetkazishga tayyor"], ["completed", "Yakunlandi"], ["cancelled", "Bekor qilindi"], ["issue", "Muammo"]];
const supplierOfferStatuses = [["draft", "Qoralama"], ["sent", "Yuborilgan"], ["received", "Olingan"], ["selected", "Tanlangan"], ["partially_selected", "Qisman tanlangan"], ["rejected", "Rad etilgan"], ["expired", "Muddati o'tgan"], ["cancelled", "Bekor qilingan"]];
const supplierInvoiceTypes = [["advance", "Avans"], ["product_purchase", "Mahsulot xaridi"], ["transport", "Transport"], ["adjustment", "Qayta hisoblash"], ["other", "Boshqa"]];
const supplierInvoiceStatuses = [["draft", "Qoralama"], ["received", "Qabul qilindi"], ["partially_paid", "Qisman to'langan"], ["paid", "To'langan"], ["overdue", "Kechikkan"], ["cancelled", "Bekor qilingan"]];
const supplierPaymentStatuses = [["paid", "Ta'minotchiga to'lov chiqdi"], ["unallocated", "Taqsimlanmagan"], ["partially_allocated", "Qisman taqsimlangan"], ["allocated", "Taqsimlangan"], ["cancelled", "Bekor qilingan"]];
const supplierFinanceDocumentTypes = [["supplier_invoice_file", "Ta'minotchi hisobi fayli"], ["payment_order", "To'lov topshiriqnomasi"], ["bank_statement", "Bank ko'chirmasi"], ["reconciliation_act", "Solishtirma dalolatnoma"], ["other", "Boshqa"]];

const transportPaymentTypes = [
  ["included", "Shartnoma summasiga kiritilgan"],
  ["separate_invoice", "Alohida hisob-faktura qilinadi"],
  ["customer_pays_directly", "Mijoz bevosita to'laydi"],
];

const deliveryMethods = [
  ["auto", "Avto"],
  ["railway", "Temiryo'l"],
  ["mixed", "Aralash"],
];

const uzTranslations = {
  "Operations": "Operatsiyalar",
  "Toggle sidebar": "Yon menyuni ochish/yopish",
  "Primary navigation": "Asosiy navigatsiya",
  "Reports": "Hisobotlar",
  "Finance": "Moliya",
  "Sales": "Sotuv",
  "Delivery": "Yetkazib berish",
  "Supply": "Ta'minot",
  "Dashboard": "Boshqaruv paneli",
  "Profit": "Foyda",
  "Cashflow": "Pul oqimi",
  "Receivables": "Debitorlik",
  "Payables": "Kreditorlik",
  "Clients": "Mijozlar",
  "Contracts": "Shartnomalar",
  "Orders": "Buyurtmalar",
  "Delivery Batches": "Yetkazib berish partiyalari",
  "Delivery batches": "Yetkazib berish partiyalari",
  "Logistics": "Logistika",
  "Customer Invoices": "Mijoz hisoblari",
  "Customer Payments": "Mijoz to'lovlari",
  "Suppliers": "Ta'minotchilar",
  "Procurements": "Xaridlar",
  "Supplier Invoices": "Ta'minotchi hisoblari",
  "Supplier Payments": "Ta'minotchi to'lovlari",
  "Reports": "Hisobotlar",
  "Basic information": "Asosiy ma'lumotlar",
  "General information": "Umumiy ma'lumotlar",
  "First contact person": "Birinchi kontakt shaxs",
  "Address": "Manzil",
  "Addresses": "Manzillar",
  "Bank account": "Bank hisobi",
  "Bank accounts": "Bank hisoblari",
  "Contacts": "Kontaktlar",
  "Documents": "Hujjatlar",
  "Notes": "Izohlar",
  "Notes / History": "Izohlar / Tarix",
  "Specification": "Spetsifikatsiya",
  "Payment terms": "To'lov shartlari",
  "Transport terms": "Transport shartlari",
  "Transport": "Transport",
  "Products": "Mahsulotlar",
  "Supplier": "Ta'minotchi",
  "Price": "Narx",
  "General": "Umumiy",
  "Loading clients...": "Mijozlar yuklanmoqda...",
  "Loading client...": "Mijoz yuklanmoqda...",
  "Loading contracts...": "Shartnomalar yuklanmoqda...",
  "Loading contract...": "Shartnoma yuklanmoqda...",
  "Loading dashboard...": "Dashboard yuklanmoqda...",
  "Legal entity profiles, contacts, addresses, documents, and notes.": "Yuridik shaxs profillari, kontaktlar, manzillar, hujjatlar va izohlar.",
  "Client contracts, product specifications, payment terms, and documents.": "Mijoz shartnomalari, mahsulot spetsifikatsiyalari, to'lov shartlari va hujjatlar.",
  "Contract data, specification, payment terms, transport terms, and documents.": "Shartnoma ma'lumotlari, spetsifikatsiya, to'lov va transport shartlari, hujjatlar.",
  "Invoice-based profit and payment-based cashflow overview.": "Hisob-fakturalar bo'yicha foyda va to'lovlar bo'yicha pul oqimi sharhi.",
  "Invoice-based profitability without VAT. Advances are excluded.": "QQSsiz hisob-faktura asosidagi foydalilik. Avanslar kiritilmaydi.",
  "Payment-based cash in, cash out, and net cashflow.": "To'lovlar bo'yicha kirim, chiqim va sof pul oqimi.",
  "Open customer invoices with remaining amount.": "Qoldiq summasi bor ochiq mijoz hisoblari.",
  "Open supplier invoices with remaining amount.": "Qoldiq summasi bor ochiq ta'minotchi hisoblari.",
  "+ New client": "+ Yangi mijoz",
  "+ New contract": "+ Yangi shartnoma",
  "+ New invoice": "+ Yangi hisob",
  "+ New payment": "+ Yangi to'lov",
  "+ New supplier": "+ Yangi ta'minotchi",
  "+ New supplier invoice": "+ Yangi ta'minotchi hisobi",
  "+ New supplier payment": "+ Yangi ta'minotchi to'lovi",
  "New client": "Yangi mijoz",
  "Edit client": "Mijozni tahrirlash",
  "New contract": "Yangi shartnoma",
  "Edit contract": "Shartnomani tahrirlash",
  "New order": "Yangi buyurtma",
  "Edit order": "Buyurtmani tahrirlash",
  "New invoice": "Yangi hisob",
  "Edit invoice": "Hisobni tahrirlash",
  "New payment": "Yangi to'lov",
  "Edit payment": "To'lovni tahrirlash",
  "New supplier": "Yangi ta'minotchi",
  "Edit supplier": "Ta'minotchini tahrirlash",
  "New supplier invoice": "Yangi ta'minotchi hisobi",
  "Edit supplier invoice": "Ta'minotchi hisobini tahrirlash",
  "New supplier payment": "Yangi ta'minotchi to'lovi",
  "Edit supplier payment": "Ta'minotchi to'lovini tahrirlash",
  "Create a legal entity client profile.": "Yuridik shaxs mijoz profilini yarating.",
  "Update client profile information.": "Mijoz profili ma'lumotlarini yangilang.",
  "Back": "Orqaga",
  "Cancel": "Bekor qilish",
  "Save": "Saqlash",
  "Search": "Qidirish",
  "View": "Ko'rish",
  "Edit": "Tahrirlash",
  "Delete": "O'chirish",
  "Download": "Yuklab olish",
  "Remove": "Olib tashlash",
  "Actions": "Amallar",
  "Create contract": "Shartnoma yaratish",
  "Create order": "Buyurtma yaratish",
  "Change status": "Statusni o'zgartirish",
  "Upload document": "Hujjat yuklash",
  "Add contact": "Kontakt qo'shish",
  "Add address": "Manzil qo'shish",
  "Add bank account": "Bank hisobi qo'shish",
  "Add document": "Hujjat qo'shish",
  "Add note": "Izoh qo'shish",
  "Add product": "Mahsulot qo'shish",
  "Add at least one valid product row.": "Kamida bitta to'g'ri mahsulot qatorini qo'shing.",
  "Client name is required.": "Mijoz nomi majburiy.",
  "Client created.": "Mijoz yaratildi.",
  "Client updated.": "Mijoz yangilandi.",
  "Contract saved.": "Shartnoma saqlandi.",
  "Saved.": "Saqlandi.",
  "Deleted.": "O'chirildi.",
  "Primary item updated.": "Asosiy element yangilandi.",
  "Request failed": "So'rov bajarilmadi",
  "Delete this item?": "Bu element o'chirilsinmi?",
  "Contract must have at least one item.": "Shartnomada kamida bitta element bo'lishi kerak.",
  "Client, contract number, contract date, and validity are required.": "Mijoz, shartnoma raqami, shartnoma sanasi va amal qilish muddati majburiy.",
  "Client name": "Mijoz nomi",
  "Name": "Nomi",
  "Full name": "F.I.Sh.",
  "Position": "Lavozim",
  "Phone": "Telefon",
  "Email": "Email",
  "Notes": "Izohlar",
  "Comment": "Izoh",
  "Primary contact": "Asosiy kontakt",
  "Address type": "Manzil turi",
  "Region": "Viloyat",
  "District": "Tuman",
  "Latitude": "Kenglik",
  "Longitude": "Uzunlik",
  "Bank name": "Bank nomi",
  "Account number": "Hisob raqami",
  "Primary account": "Asosiy hisob",
  "Client": "Mijoz",
  "Contract": "Shartnoma",
  "Order": "Buyurtma",
  "Batch": "Partiya",
  "Product": "Mahsulot",
  "Code": "Kod",
  "Unit": "Birlik",
  "Quantity": "Miqdor",
  "Unit price": "Birlik narxi",
  "VAT": "QQS",
  "VAT %": "QQS %",
  "VAT amount": "QQS summasi",
  "Subtotal": "Oraliq summa",
  "Total": "Jami",
  "Total amount": "Jami summa",
  "Total quantity": "Jami miqdor",
  "Amount": "Summa",
  "Currency": "Valyuta",
  "Status": "Status",
  "Date": "Sana",
  "Created at": "Yaratilgan",
  "Updated at": "Yangilangan",
  "Created by": "Yaratgan",
  "Uploaded date": "Yuklangan sana",
  "Uploaded by": "Yuklagan",
  "Document title": "Hujjat nomi",
  "Document type": "Hujjat turi",
  "File URL": "Fayl URL",
  "Type": "Turi",
  "Employee/User": "Xodim/Foydalanuvchi",
  "Primary": "Asosiy",
  "Set as primary": "Asosiy qilish",
  "View on map": "Xaritada ko'rish",
  "Legal address": "Yuridik manzil",
  "Loading address": "Yuklash manzili",
  "Active contracts": "Aktiv shartnomalar",
  "Active orders": "Aktiv buyurtmalar",
  "Last activity": "Oxirgi faollik",
  "No clients found.": "Mijozlar topilmadi.",
  "No contacts yet.": "Kontaktlar hali yo'q.",
  "No addresses yet.": "Manzillar hali yo'q.",
  "No bank accounts yet.": "Bank hisoblari hali yo'q.",
  "No documents yet.": "Hujjatlar hali yo'q.",
  "No notes yet.": "Izohlar hali yo'q.",
  "No contracts found.": "Shartnomalar topilmadi.",
  "No payments found.": "To'lovlar topilmadi.",
  "No supplier payments found.": "Ta'minotchi to'lovlari topilmadi.",
  "Open the Contracts section to view and filter contracts for this client.": "Bu mijoz shartnomalarini ko'rish va filtrlash uchun Shartnomalar bo'limini oching.",
  "module will be added in a future stage.": "moduli keyingi bosqichda qo'shiladi.",
  "Contract-level document metadata can be added from the Documents tab after saving.": "Shartnoma hujjatlari ma'lumotlarini saqlagandan keyin Hujjatlar sahifasidan qo'shish mumkin.",
  "Contract number": "Shartnoma raqami",
  "Contract date": "Shartnoma sanasi",
  "Valid until": "Amal qilish muddati",
  "Title": "Sarlavha",
  "Delivered": "Yetkazilgan",
  "Remaining": "Qoldiq",
  "Paid amount": "To'langan summa",
  "Remaining payment": "Qolgan to'lov",
  "Transport expenses": "Transport xarajatlari",
  "Advance amount": "Avans summasi",
  "Advance percent": "Avans foizi",
  "Remaining percent": "Qoldiq foizi",
  "Advance due days": "Avans muddati, kun",
  "Batch payment due days": "Partiya to'lovi muddati, kun",
  "Remaining payment rule": "Qoldiq to'lov qoidasi",
  "Transport payment type": "Transport to'lovi turi",
  "Delivery method": "Yetkazib berish usuli",
  "Payment of the remaining amount is made per ready delivery batch based on invoice.": "Qolgan summa tayyor partiya bo'yicha hisob-faktura asosida to'lanadi.",
  "valid until": "amal qilish muddati",
  "Draft": "Qoralama",
  "Active": "Aktiv",
  "Completed": "Yakunlangan",
  "Cancelled": "Bekor qilingan",
  "Legal": "Yuridik",
  "Warehouse": "Ombor",
  "Railway station": "Temiryo'l stansiyasi",
  "Requisites": "Rekvizitlar",
  "Certificate": "Sertifikat",
  "Power of attorney": "Ishonchnoma",
  "Company card": "Kompaniya kartasi",
  "Other": "Boshqa",
  "Contract PDF": "Shartnoma PDF",
  "Additional agreement": "Qo'shimcha kelishuv",
  "Invoice": "Hisob",
  "Act": "Dalolatnoma",
  "Direct": "To'g'ridan-to'g'ri",
  "Russia direct": "Rossiyadan to'g'ridan-to'g'ri",
  "Uzbekistan local": "O'zbekiston ichki",
  "Supplier": "Ta'minotchi",
  "Acceptance act": "Qabul dalolatnomasi",
  "Quality certificate": "Sifat sertifikati",
  "Supplier invoice": "Ta'minotchi hisobi",
  "Customer invoice": "Mijoz hisobi",
  "Photo": "Foto",
  "Advance": "Avans",
  "Batch payment": "Partiya to'lovi",
  "Adjustment": "Qayta hisoblash",
  "Bank orqali": "Bank orqali",
  "Invoice file": "Hisob fayli",
  "Payment order": "To'lov topshiriqnomasi",
  "Bank statement": "Bank ko'chirmasi",
  "Reconciliation act": "Solishtirma dalolatnoma",
  "Loading": "Yuklanmoqda",
  "Factory": "Zavod",
  "Supplier search": "Ta'minotchi qidirish",
  "Offers received": "Takliflar olindi",
  "Supplier selected": "Ta'minotchi tanlangan",
  "Supplier confirmed": "Ta'minotchi tasdiqlagan",
  "Purchase approved": "Xarid tasdiqlangan",
  "Waiting supplier": "Ta'minotchi kutilmoqda",
  "Ready for pickup": "Olib ketishga tayyor",
  "Ready for delivery": "Yetkazishga tayyor",
  "Issue": "Muammo",
  "Sent": "Yuborilgan",
  "Received": "Qabul qilingan",
  "Selected": "Tanlangan",
  "Partially selected": "Qisman tanlangan",
  "Rejected": "Rad etilgan",
  "Expired": "Muddati o'tgan",
  "Transport": "Transport",
  "Included": "Kiritilgan",
  "Separate invoice": "Alohida hisob",
  "Customer pays directly": "Mijoz to'g'ridan-to'g'ri to'laydi",
  "Auto": "Avto",
  "Railway": "Temiryo'l",
  "Mixed": "Aralash",
  "Invoice number": "Hisob raqami",
  "Invoice date": "Hisob sanasi",
  "Due date": "To'lov muddati",
  "Paid": "To'langan",
  "Paid amount": "To'langan summa",
  "Remaining amount": "Qolgan summa",
  "Partially paid": "Qisman to'langan",
  "Overdue": "Muddati o'tgan",
  "Payment number": "To'lov raqami",
  "Payment date": "To'lov sanasi",
  "Payment method": "To'lov usuli",
  "Method": "Usul",
  "Bank account": "Bank hisobi",
  "Reference": "Ma'lumotnoma",
  "Reference number": "Ma'lumotnoma raqami",
  "Allocated": "Taqsimlangan",
  "Unallocated": "Taqsimlanmagan",
  "Allocate amount": "Taqsimlash summasi",
  "Manual allocation": "Qo'lda taqsimlash",
  "Open invoice": "Ochiq hisob",
  "Leave unallocated": "Taqsimlanmagan qoldirish",
  "For multiple allocations, create the payment then add allocations through the API/detail workflow.": "Bir nechta taqsimlash uchun avval to'lov yarating, keyin detail/API orqali taqsimlash qo'shing.",
  "Customer-side payment receipts and allocation status.": "Mijoz to'lov tushumlari va taqsimlash holati.",
  "Supplier payments and invoice allocations.": "Ta'minotchi to'lovlari va hisob bo'yicha taqsimlash.",
  "Payment saved.": "To'lov saqlandi.",
  "Supplier payment saved.": "Ta'minotchi to'lovi saqlandi.",
  "Payment amount": "To'lov summasi",
  "Payment date": "To'lov sanasi",
  "Payment order": "To'lov topshiriqnomasi",
  "Allocations": "Taqsimlashlar",
  "No allocations.": "Taqsimlashlar yo'q.",
  "No customer payments.": "Mijoz to'lovlari yo'q.",
  "No supplier payments.": "Ta'minotchi to'lovlari yo'q.",
  "Recent payments": "So'nggi to'lovlar",
  "Recent customer payments": "So'nggi mijoz to'lovlari",
  "Recent supplier payments": "So'nggi ta'minotchi to'lovlari",
  "Revenue": "Daromad",
  "Customer payments": "Mijoz to'lovlari",
  "Supplier cost": "Ta'minotchi xarajati",
  "Supplier payments": "Ta'minotchi to'lovlari",
  "Logistics cost": "Logistika xarajati",
  "Gross profit": "Yalpi foyda",
  "Profit margin": "Foyda marjasi",
  "Net cashflow": "Sof pul oqimi",
  "Customer receivables": "Mijoz debitorligi",
  "Supplier payables": "Ta'minotchi kreditorligi",
  "Top profitable orders": "Eng foydali buyurtmalar",
  "Orders with negative profit": "Zarar bilan buyurtmalar",
  "No profitable orders yet.": "Foydali buyurtmalar hali yo'q.",
  "No negative profit orders.": "Zarar bilan buyurtmalar yo'q.",
  "Profit rows": "Foyda qatorlari",
  "By orders": "Buyurtmalar bo'yicha",
  "By contracts": "Shartnomalar bo'yicha",
  "By clients": "Mijozlar bo'yicha",
  "By batches": "Partiyalar bo'yicha",
  "Cash in": "Kirim",
  "Cash out": "Chiqim",
  "Net cashflow": "Sof pul oqimi",
  "Daily": "Kunlik",
  "Monthly": "Oylik",
  "Daily cashflow": "Kunlik pul oqimi",
  "Monthly cashflow": "Oylik pul oqimi",
  "Month": "Oy",
  "No cashflow rows.": "Pul oqimi qatorlari yo'q.",
  "Total receivables": "Jami debitorlik",
  "Overdue": "Muddati o'tgan",
  "Current": "Joriy",
  "Paid this month": "Bu oy to'langan",
  "Top debtors": "Eng katta qarzdorlar",
  "Receivable invoices": "Debitorlik hisoblari",
  "No receivables.": "Debitorlik yo'q.",
  "Total payables": "Jami kreditorlik",
  "Top suppliers": "Eng katta ta'minotchilar",
  "Payable invoices": "Kreditorlik hisoblari",
  "No payables.": "Kreditorlik yo'q.",
  "Procurement": "Xarid",
  "Procurement number": "Xarid raqami",
  "Known supplier": "Ma'lum ta'minotchi",
  "Select client": "Mijozni tanlang",
  "Select supplier": "Ta'minotchini tanlang",
  "Payment, client, reference, bank": "To'lov, mijoz, ma'lumotnoma, bank",
  "Payment, supplier, reference, bank": "To'lov, ta'minotchi, ma'lumotnoma, bank",
};

Object.assign(uzTranslations, {
  "Operational demand under an existing client contract.": "Mavjud mijoz shartnomasi bo'yicha operatsion talab.",
  "Operational demands under client contracts.": "Mijoz shartnomalari bo'yicha operatsion talablar.",
  "Select a contract first.": "Avval shartnomani tanlang.",
  "Select an order first.": "Avval buyurtmani tanlang.",
  "Order must have at least one item.": "Buyurtmada kamida bitta element bo'lishi kerak.",
  "Contract, order number, and order date are required.": "Shartnoma, buyurtma raqami va buyurtma sanasi majburiy.",
  "Add at least one product from the contract.": "Shartnomadan kamida bitta mahsulot qo'shing.",
  "Order saved.": "Buyurtma saqlandi.",
  "Supplier selected.": "Ta'minotchi tanlandi.",
  "Supplier confirmed.": "Ta'minotchi tasdiqlandi.",
  "Loading orders...": "Buyurtmalar yuklanmoqda...",
  "Loading order...": "Buyurtma yuklanmoqda...",
  "Order number": "Buyurtma raqami",
  "Order date": "Buyurtma sanasi",
  "Source": "Manba",
  "Delivery model": "Yetkazib berish modeli",
  "No orders found.": "Buyurtmalar topilmadi.",
  "Ordered quantity": "Buyurtma miqdori",
  "Required date": "Kerakli sana",
  "Source type": "Manba turi",
  "Edit products": "Mahsulotlarni tahrirlash",
  "Delivery / Batches": "Yetkazib berish / Partiyalar",
  "Price and logistics": "Narx va logistika",
  "Product subtotal": "Mahsulot oraliq summasi",
  "Markup percent": "Ustama foizi",
  "Markup amount": "Ustama summasi",
  "Logistics price": "Logistika narxi",
  "Contract remaining": "Shartnoma qoldig'i",
  "Total with VAT": "QQS bilan jami",
  "Items": "Elementlar",
  "No specification items.": "Spetsifikatsiya elementlari yo'q.",
  "Order-level document metadata can be added from the Documents tab after saving.": "Buyurtma hujjatlari ma'lumotlarini saqlagandan keyin Hujjatlar sahifasidan qo'shish mumkin.",
  "Partial shipment under an existing order.": "Mavjud buyurtma bo'yicha qisman jo'natma.",
  "Partial shipment tracking under orders.": "Buyurtmalar bo'yicha qisman jo'natmalar nazorati.",
  "Edit delivery batch": "Partiyani tahrirlash",
  "New delivery batch": "Yangi partiya",
  "+ New batch": "+ Yangi partiya",
  "Batch must have at least one item.": "Partiyada kamida bitta element bo'lishi kerak.",
  "Order, batch number, and batch date are required.": "Buyurtma, partiya raqami va partiya sanasi majburiy.",
  "Add at least one order product.": "Kamida bitta buyurtma mahsulotini qo'shing.",
  "Delivery batch saved.": "Yetkazib berish partiyasi saqlandi.",
  "Loading delivery batches...": "Yetkazib berish partiyalari yuklanmoqda...",
  "Loading delivery batch...": "Yetkazib berish partiyasi yuklanmoqda...",
  "Batch number": "Partiya raqami",
  "Batch date": "Partiya sanasi",
  "Batch, order, client, product": "Partiya, buyurtma, mijoz, mahsulot",
  "Planned": "Rejalashtirilgan",
  "Loaded": "Yuklangan",
  "Accepted": "Qabul qilingan",
  "Difference": "Farq",
  "No delivery batches found.": "Yetkazib berish partiyalari topilmadi.",
  "Open logistics": "Logistikani ochish",
  "Logistics status": "Logistika statusi",
  "Batch-level document metadata can be added from the Documents tab after saving.": "Partiya hujjatlari ma'lumotlarini saqlagandan keyin Hujjatlar sahifasidan qo'shish mumkin.",
  "Transport tracking for delivery batches.": "Yetkazib berish partiyalari uchun transport nazorati.",
  "Batch, carrier, driver, vehicle, client": "Partiya, tashuvchi, haydovchi, transport, mijoz",
  "Fulfillment": "Bajarish turi",
  "Carrier": "Tashuvchi",
  "Driver": "Haydovchi",
  "Driver phone": "Haydovchi telefoni",
  "Vehicle": "Transport raqami",
  "Trailer": "Tirkama",
  "Planned pickup": "Rejadagi yuklash",
  "Planned delivery": "Rejadagi yetkazish",
  "Actual pickup": "Haqiqiy yuklash",
  "Actual delivery": "Haqiqiy yetkazish",
  "Transport details": "Transport tafsilotlari",
  "Cost": "Xarajat",
  "Cost amount": "Xarajat summasi",
  "Customer price": "Mijoz narxi",
  "Paid by": "Kim to'laydi",
  "Open batch": "Partiyani ochish",
  "No logistics records found.": "Logistika yozuvlari topilmadi.",
  "No logistics documents yet.": "Logistika hujjatlari hali yo'q.",
  "No logistics notes yet.": "Logistika izohlari hali yo'q.",
  "Customer invoice and manual items.": "Mijoz hisobi va qo'lda kiritilgan elementlar.",
  "Customer-side invoices and payment status.": "Mijoz hisoblari va to'lov statusi.",
  "Invoice items": "Hisob elementlari",
  "Add item": "Element qo'shish",
  "Invoice must have at least one item.": "Hisobda kamida bitta element bo'lishi kerak.",
  "Invoice saved.": "Hisob saqlandi.",
  "Finance documents can be added from detail pages.": "Moliya hujjatlarini detail sahifalaridan qo'shish mumkin.",
  "Invoice, client, contract, order, batch": "Hisob, mijoz, shartnoma, buyurtma, partiya",
  "No invoices found.": "Hisoblar topilmadi.",
  "No items.": "Elementlar yo'q.",
  "Description": "Tavsif",
  "Payments / Allocations": "To'lovlar / Taqsimlashlar",
  "Payment ID": "To'lov ID",
  "Invoice ID": "Hisob ID",
  "Created": "Yaratilgan",
  "Updated": "Yangilangan",
  "Uploaded": "Yuklangan",
  "Allocate payment": "To'lovni taqsimlash",
  "Supplier-side invoice with manual items and allocation support.": "Ta'minotchi hisobi, qo'lda kiritilgan elementlar va taqsimlash imkoniyati.",
  "Supplier-side invoices, payment status, and balances.": "Ta'minotchi hisoblari, to'lov statusi va qoldiqlar.",
  "Supplier invoice saved.": "Ta'minotchi hisobi saqlandi.",
  "Supplier finance document metadata can be added from detail/API workflow.": "Ta'minotchi moliya hujjatlari ma'lumotlarini detail/API orqali qo'shish mumkin.",
  "Supplier payment with optional manual invoice allocation.": "Hisobga qo'lda taqsimlash imkoniyati bor ta'minotchi to'lovi.",
  "Supplier payment document metadata can be added later.": "Ta'minotchi to'lov hujjatlari ma'lumotlarini keyin qo'shish mumkin.",
  "Invoice, supplier, procurement, batch": "Hisob, ta'minotchi, xarid, partiya",
  "No supplier invoices found.": "Ta'minotchi hisoblari topilmadi.",
  "Supplier offer": "Ta'minotchi taklifi",
  "Supplier offer ID": "Ta'minotchi taklifi ID",
  "Delivery batch ID": "Partiya ID",
  "Logistics ID": "Logistika ID",
  "Select procurement": "Xaridni tanlang",
  "Supplier name": "Ta'minotchi nomi",
  "Offer number": "Taklif raqami",
  "Offer date": "Taklif sanasi",
  "Estimated delivery cost": "Taxminiy yetkazish xarajati",
  "Delivery terms": "Yetkazib berish shartlari",
  "Save offer": "Taklifni saqlash",
  "Supplier offer saved.": "Ta'minotchi taklifi saqlandi.",
  "Selection updated.": "Tanlov yangilandi.",
  "Supplier offer confirmed.": "Ta'minotchi taklifi tasdiqlandi.",
  "Add supplier option": "Ta'minotchi taklifini qo'shish",
  "Edit supplier option": "Ta'minotchi taklifini tahrirlash",
  "Offered price": "Birlik xarid narxi",
  "Available quantity": "Mavjud miqdor",
  "Ready date": "Tayyor bo'lish sanasi",
  "+ Create batch": "+ Partiya yaratish",
  "Create batch": "Partiya yaratish",
  "No supplier options yet.": "Ta'minotchi variantlari hali yo'q.",
  "Select": "Tanlash",
  "Confirm": "Tasdiqlash",
  "Selected": "Tanlangan",
  "Manual supplier": "Qo'lda kiritilgan ta'minotchi",
  "Product purchase": "Mahsulot xaridi",
  "Margin": "Marja",
  "Customer": "Mijoz",
  "Customer payment": "Mijoz to'lovi",
  "Supplier payment": "Ta'minotchi to'lovi",
  "Overdue days": "Kechikkan kunlar",
  "Customer-side payment receipts and allocation status.": "Mijoz to'lov tushumlari va taqsimlash statusi.",
  "Bank": "Bank",
  "Coordinates": "Koordinatalar",
  "User": "Foydalanuvchi",
  "Delivery Batches": "Partiyalar",
  "Edit delivery batch": "Partiyani tahrirlash",
  "New delivery batch": "Yangi partiya",
  "Partial shipment under an existing order.": "Mavjud buyurtma bo'yicha qisman jo'natma.",
  "Partial shipment tracking under orders.": "Buyurtmalar bo'yicha partiyalar nazorati.",
  "Loading delivery batches...": "Partiyalar yuklanmoqda...",
  "Loading delivery batch...": "Partiya yuklanmoqda...",
  "+ New batch": "+ Yangi partiya",
  "Batch, order, client, product": "Partiya, buyurtma, mijoz, mahsulot",
  "Batch number": "Partiya raqami",
  "Batch date": "Partiya sanasi",
  "Select product": "Mahsulotni tanlang",
  "Select order": "Buyurtmani tanlang",
  "Order balance": "Buyurtma qoldig'i",
  "left": "qoldi",
  "planned": "rejalashtirilgan",
  "accepted": "qabul qilingan",
  "Planned": "Reja",
  "Loaded": "Yuklangan",
  "Accepted": "Qabul qilingan",
  "Difference": "Farq",
  "Delivery info": "Yetkazib berish ma'lumotlari",
  "Fulfillment type": "Yetkazib berish modeli",
  "Source type": "Manba",
  "Delivery method": "Yetkazib berish usuli",
  "Supplier name": "Ta'minotchi nomi",
  "Supplier status": "Ta'minotchi statusi",
  "Selected supplier": "Tanlangan ta'minotchi",
  "Supplier notes": "Ta'minotchi izohlari",
  "Xarid jarayonida avtomatik tanlanadi": "Xarid jarayonida avtomatik tanlanadi",
  "Logistics auto-created info": "Logistika ma'lumotlari",
  "Logistics status": "Logistika statusi",
  "Vehicle number": "Transport raqami",
  "Trailer number": "Tirkama raqami",
  "Logistics notes": "Logistika izohlari",
  "Open logistics": "Logistikani ochish",
  "Open logistics detail": "Logistika tafsilotini ochish",
  "Upload document": "Hujjat yuklash",
  "No delivery batches found.": "Partiyalar topilmadi.",
  "No products yet.": "Mahsulotlar hali yo'q.",
  "Batch must have at least one item.": "Partiyada kamida bitta element bo'lishi kerak.",
  "Order, batch number, and batch date are required.": "Buyurtma, partiya raqami va partiya sanasi majburiy.",
  "Add at least one order product.": "Kamida bitta buyurtma mahsulotini qo'shing.",
  "Delivery batch saved.": "Partiya saqlandi.",
  "Batch-level document metadata can be added from the Documents tab after saving.": "Partiya hujjatlari ma'lumotlarini saqlagandan keyin Hujjatlar sahifasidan qo'shish mumkin.",
  "Planned loading": "Rejadagi yuklash",
  "Planned loading date": "Rejadagi yuklash sanasi",
  "Planned delivery date": "Rejadagi yetkazish sanasi",
  "Actual loading": "Haqiqiy yuklash",
  "Actual loading date": "Haqiqiy yuklash sanasi",
  "Actual delivery date": "Haqiqiy yetkazish sanasi",
  "Accepted date": "Qabul sanasi",
  "Delivery address": "Yetkazish manzili",
  "Actual delivery": "Haqiqiy yetkazish",
  "Planned delivery": "Rejadagi yetkazish",
  "Actual pickup": "Haqiqiy yuklash",
  "Planned pickup": "Rejadagi yuklash",
  "Yuklangan va qabul qilingan miqdor farq qiladi.": "Yuklangan va qabul qilingan miqdor farq qiladi.",
  "not_assigned": "Biriktirilmagan",
  "carrier_search": "Tashuvchi qidirilmoqda",
  "carrier_assigned": "Tashuvchi biriktirildi",
  "vehicle_assigned": "Transport biriktirildi",
  "in_transit": "Yo'lda",
  "quantity_difference": "Miqdor farqi bor",
  "ready_for_loading": "Yuklashga tayyor",
  "supplier_preparing": "Ta'minotchi tayyorlamoqda",
  "waiting_payment": "To'lov kutilmoqda",
  "documents_pending": "Hujjatlar kutilmoqda",
});

