async function renderDashboardOverview() {
  app.innerHTML = `<div class="page ops-page"><div class="empty">Boshqaruv paneli yuklanmoqda...</div></div>`;
  const data = await api("/api/dashboard/overview");
  const s = data.summary;
  const attention = [];
  if (Number(s.customer_receivables) > 0) attention.push(["Mijoz debitorligi", fmtMoney(s.customer_receivables), "/receivables"]);
  if (Number(s.supplier_payables) > 0) attention.push(["Ta'minotchi kreditorligi", fmtMoney(s.supplier_payables), "/payables"]);
  if ((data.negative_profit_orders || []).length) attention.push(["Manfiy foyda buyurtmalar", `${data.negative_profit_orders.length} ta`, "/profit"]);
  if (Number(s.net_cashflow) < 0) attention.push(["Sof pul oqimi manfiy", fmtMoney(s.net_cashflow), "/cashflow"]);
  app.innerHTML = opsPageShell("Boshqaruv paneli", [{label:"Boshqaruv paneli",active:true},{label:"Foyda",path:"/profit"},{label:"Pul oqimi",path:"/cashflow"}], `${summaryCards([["Daromad",fmtMoney(s.revenue_subtotal)],["Mijoz to'lovlari",fmtMoney(s.customer_payments_received)],["Ta'minot xarajati",fmtMoney(s.supplier_purchase_cost_subtotal)],["Ta'minotchi to'lovlari",fmtMoney(s.supplier_payments_made)],["Logistika xarajati",fmtMoney(s.logistics_cost)],["Yalpi foyda",fmtMoney(s.gross_profit), Number(s.gross_profit)<0?"negative":""],["Foyda marjasi",fmtPercent(s.profit_margin)],["Sof pul oqimi",fmtMoney(s.net_cashflow), Number(s.net_cashflow)<0?"negative":""],["Debitorlik",fmtMoney(s.customer_receivables)],["Kreditorlik",fmtMoney(s.supplier_payables)]])}${section("E'tibor kerak", attention.length ? `<div class="attention-grid">${attention.map(([title,value,path])=>`<button class="attention-card" type="button" data-nav="${path}"><span>${title}</span><strong>${value}</strong></button>`).join("")}</div>` : `<div class="empty">Hozircha alohida e'tibor talab qiladigan holat yo'q.</div>`)}${workflowNextActionPanel(attention.length ? {title:"Eng muhim ochiq moliyaviy va operatsion holatlarni ko'rib chiqing",button:"Debitorlikni ochish",path:"/receivables"} : {title:"Kunlik ko'rsatkichlarni kuzatishda davom eting",button:"Foydani ko'rish",path:"/profit",done:true})}${opsTableOrEmpty(data.top_profitable_orders,["Buyurtma","Mijoz","Daromad","Ta'minot xarajati","Logistika","Yalpi foyda","Marja"],(r)=>`<tr><td>${fmt(r.order_number)}</td><td>${fmt(r.client_name)}</td><td class="ops-money">${fmtMoney(r.revenue_subtotal)}</td><td class="ops-money">${fmtMoney(r.supplier_purchase_cost_subtotal)}</td><td class="ops-money">${fmtMoney(r.logistics_cost)}</td><td class="ops-money ${Number(r.gross_profit)<0?"negative":""}">${fmtMoney(r.gross_profit)}</td><td>${fmtPercent(r.profit_margin)}</td></tr>`,"Foydali buyurtmalar hali yo'q.")}${opsTableOrEmpty(data.negative_profit_orders,["Manfiy foyda buyurtma","Mijoz","Daromad","Xarajat","Yalpi foyda"],(r)=>`<tr><td>${fmt(r.order_number)}</td><td>${fmt(r.client_name)}</td><td class="ops-money">${fmtMoney(r.revenue_subtotal)}</td><td class="ops-money">${fmtMoney(Number(r.supplier_purchase_cost_subtotal)+Number(r.logistics_cost))}</td><td class="ops-money negative">${fmtMoney(r.gross_profit)}</td></tr>`,"Manfiy foyda buyurtmalar yo'q.")}`);
}

function profitTable(rows, mode) {
  if (mode === "contracts") return opsTableOrEmpty(rows,["Shartnoma","Mijoz","Daromad","Ta'minot xarajati","Logistika","Yalpi foyda","Marja","Mijoz qoldig'i","Ta'minotchi qoldig'i"],(r)=>`<tr><td>${fmt(r.contract_number)}</td><td>${fmt(r.client_name)}</td><td class="ops-money">${fmtMoney(r.revenue_subtotal)}</td><td class="ops-money">${fmtMoney(r.supplier_purchase_cost_subtotal)}</td><td class="ops-money">${fmtMoney(r.logistics_cost)}</td><td class="ops-money ${Number(r.gross_profit)<0?"negative":""}">${fmtMoney(r.gross_profit)}</td><td>${fmtPercent(r.profit_margin)}</td><td class="ops-money">${fmtMoney(r.customer_remaining)}</td><td class="ops-money">${fmtMoney(r.supplier_remaining)}</td></tr>`,"Shartnoma foydasi topilmadi.");
  if (mode === "clients") return opsTableOrEmpty(rows,["Mijoz","Daromad","To'langan","Qoldiq","Ta'minot xarajati","Logistika","Yalpi foyda","Marja","Muddati o'tgan"],(r)=>`<tr><td>${fmt(r.client_name)}</td><td class="ops-money">${fmtMoney(r.revenue_subtotal)}</td><td class="ops-money">${fmtMoney(r.customer_paid)}</td><td class="ops-money">${fmtMoney(r.customer_remaining)}</td><td class="ops-money">${fmtMoney(r.supplier_purchase_cost_subtotal)}</td><td class="ops-money">${fmtMoney(r.logistics_cost)}</td><td class="ops-money ${Number(r.gross_profit)<0?"negative":""}">${fmtMoney(r.gross_profit)}</td><td>${fmtPercent(r.profit_margin)}</td><td class="ops-money">${fmtMoney(r.overdue_amount)}</td></tr>`,"Mijoz foydasi topilmadi.");
  if (mode === "batches") return opsTableOrEmpty(rows,["Partiya","Buyurtma","Mijoz","Ta'minotchi","Qabul qilingan","Daromad","Ta'minot xarajati","Logistika","Yalpi foyda","Marja","Status"],(r)=>`<tr><td>${fmt(r.batch_number)}</td><td>${fmt(r.order_number)}</td><td>${fmt(r.client_name)}</td><td>${fmt(r.supplier_name)}</td><td>${fmtQty(r.accepted_quantity)}</td><td class="ops-money">${fmtMoney(r.revenue_subtotal)}</td><td class="ops-money">${fmtMoney(r.supplier_purchase_cost_subtotal)}</td><td class="ops-money">${fmtMoney(r.logistics_cost)}</td><td class="ops-money ${Number(r.gross_profit)<0?"negative":""}">${fmtMoney(r.gross_profit)}</td><td>${fmtPercent(r.profit_margin)}</td><td>${fmt(r.batch_status)}</td></tr>`,"Partiya foydasi topilmadi.");
  return opsTableOrEmpty(rows,["Buyurtma","Mijoz","Shartnoma","Daromad","Ta'minot xarajati","Logistika","Yalpi foyda","Marja","Mijoz qoldig'i","Ta'minotchi qoldig'i","Status"],(r)=>`<tr><td>${fmt(r.order_number)}</td><td>${fmt(r.client_name)}</td><td>${fmt(r.contract_number)}</td><td class="ops-money">${fmtMoney(r.revenue_subtotal)}</td><td class="ops-money">${fmtMoney(r.supplier_purchase_cost_subtotal)}</td><td class="ops-money">${fmtMoney(r.logistics_cost)}</td><td class="ops-money ${Number(r.gross_profit)<0?"negative":""}">${fmtMoney(r.gross_profit)}</td><td>${fmtPercent(r.profit_margin)}</td><td class="ops-money">${fmtMoney(r.customer_remaining)}</td><td class="ops-money">${fmtMoney(r.supplier_remaining)}</td><td>${fmt(r.order_status)}</td></tr>`,"Buyurtma foydasi topilmadi.");
}

async function renderProfitPage() {
  const tab = new URLSearchParams(location.search).get("tab") || "orders";
  const path = tab === "contracts" ? "contracts" : tab === "clients" ? "clients" : tab === "batches" ? "batches" : "orders";
  const data = await api(`/api/dashboard/profit/${path}?page_size=100`);
  app.innerHTML = opsPageShell("Foyda", [["orders","Buyurtmalar"],["contracts","Shartnomalar"],["clients","Mijozlar"],["batches","Partiyalar"]].map(([k,l])=>({label:l,path:`/profit?tab=${k}`,active:tab===k})), profitTable(data.items, path));
}

async function renderCashflowPage() {
  const tab = new URLSearchParams(location.search).get("tab") || "daily";
  const rows = await api(`/api/dashboard/cashflow/${tab === "monthly" ? "monthly" : "daily"}`);
  app.innerHTML = opsPageShell("Pul oqimi", [{label:"Kunlik",path:"/cashflow?tab=daily",active:tab==="daily"},{label:"Oylik",path:"/cashflow?tab=monthly",active:tab==="monthly"}], opsTableOrEmpty(rows,[tab==="monthly"?"Oy":"Sana","Kirim","Chiqim","Sof pul oqimi"],(r)=>`<tr><td>${fmt(r.month || r.date)}</td><td class="ops-money">${fmtMoney(r.cash_in)}</td><td class="ops-money">${fmtMoney(r.cash_out)}</td><td class="ops-money ${Number(r.net_cashflow)<0?"negative":""}">${fmtMoney(r.net_cashflow)}</td></tr>`,"Pul oqimi yozuvlari topilmadi."));
}

async function renderReceivablesPage() {
  const data = await api("/api/dashboard/receivables");
  const s = data.summary;
  app.innerHTML = opsPageShell("Debitorlik", [{label:"Debitorlik",active:true},{label:"Mijoz hisoblari",path:"/customer-invoices"},{label:"Mijoz to'lovlari",path:"/customer-payments"}], `${summaryCards([["Jami debitorlik",fmtMoney(s.total_receivables)],["Muddati o'tgan",fmtMoney(s.overdue_receivables)],["Joriy",fmtMoney(s.current_receivables)],["Bu oy to'langan",fmtMoney(s.paid_this_month)],["Asosiy qarzdorlar",s.top_debtors.map((d)=>`${esc(d.name)}: ${fmtMoney(d.amount)}`).join("<br>") || dash]])}${opsTableOrEmpty(data.items,["Mijoz","Hisob","Turi","To'lov muddati","Jami","To'langan","Qoldiq","Kechikkan kun","Status","Shartnoma","Buyurtma","Partiya"],(r)=>`<tr><td>${fmt(r.customer_name)}</td><td>${fmt(r.invoice_number)}</td><td>${fmt(optionLabel(invoiceTypes,r.invoice_type))}</td><td>${fmt(r.due_date)}</td><td class="ops-money">${fmtMoney(r.total_amount)}</td><td class="ops-money">${fmtMoney(r.paid_amount)}</td><td class="ops-money ${numberValue(r.remaining_amount)>0?"ops-warning":""}">${fmtMoney(r.remaining_amount)}</td><td class="${r.overdue_days>0?"negative":""}">${fmt(r.overdue_days)}</td><td>${statusBadge(r.status)}</td><td>${fmt(r.contract_number)}</td><td>${fmt(r.order_number)}</td><td>${fmt(r.batch_number)}</td></tr>`,"Debitorlik topilmadi.")}`, "receivables-ops-page");
}

async function renderPayablesPage() {
  const data = await api("/api/dashboard/payables");
  const s = data.summary;
  app.innerHTML = opsPageShell("Kreditorlik", [{label:"Kreditorlik",active:true},{label:"Ta'minotchi hisoblari",path:"/supplier-invoices"},{label:"Ta'minotchi to'lovlari",path:"/supplier-payments"}], `${summaryCards([["Jami kreditorlik",fmtMoney(s.total_payables)],["Muddati o'tgan",fmtMoney(s.overdue_payables)],["Joriy",fmtMoney(s.current_payables)],["Bu oy to'langan",fmtMoney(s.paid_this_month)],["Asosiy ta'minotchilar",s.top_suppliers_by_payable.map((d)=>`${esc(d.name)}: ${fmtMoney(d.amount)}`).join("<br>") || dash]])}${opsTableOrEmpty(data.items,["Ta'minotchi","Hisob","Turi","To'lov muddati","Jami","To'langan","Qoldiq","Kechikkan kun","Status","Xarid","Partiya"],(r)=>`<tr><td>${fmt(r.supplier_name)}</td><td>${fmt(r.invoice_number)}</td><td>${fmt(optionLabel(supplierInvoiceTypes,r.invoice_type))}</td><td>${fmt(r.due_date)}</td><td class="ops-money">${fmtMoney(r.total_amount)}</td><td class="ops-money">${fmtMoney(r.paid_amount)}</td><td class="ops-money ${numberValue(r.remaining_amount)>0?"ops-warning":""}">${fmtMoney(r.remaining_amount)}</td><td class="${r.overdue_days>0?"negative":""}">${fmt(r.overdue_days)}</td><td>${statusBadge(r.status)}</td><td>${fmt(r.procurement_number)}</td><td>${fmt(r.batch_number)}</td></tr>`,"Kreditorlik topilmadi.")}`, "payables-ops-page");
}

